/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-18 15:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.Member;
import controller.member.*;
import dao.*;
import util.*;

public final class listMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("controller.member");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>Dashboard - NiceAdmin Bootstrap Template</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link href=\"/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("<link href=\"/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/quill.bubble.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Template Main CSS File -->\r\n");
      out.write("<link href=\"css/stylex.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Updated: Apr 20 2024 with Bootstrap v5.3.3\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Header ======= -->\r\n");
      out.write("	<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("			<a href=\"books\" class=\"logo d-flex align-items-center\"> <img\r\n");
      out.write("				src=\"assets/img/logo.png\" alt=\"\"> <span\r\n");
      out.write("				class=\"d-none d-lg-block\">NiceAdmin</span>\r\n");
      out.write("			</a> <i class=\"bi bi-list toggle-sidebar-btn\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"search-bar\">\r\n");
      out.write("			<form class=\"search-form d-flex align-items-center\" method=\"GET\"\r\n");
      out.write("				action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search-member\">\r\n");
      out.write("				<input type=\"text\" name=\"searchName\" placeholder=\"Tìm kiếm\"\r\n");
      out.write("					title=\"Enter search keyword\">\r\n");
      out.write("				<button type=\"submit\" title=\"Search\">\r\n");
      out.write("					<i class=\"bi bi-search\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Search Bar -->\r\n");
      out.write("\r\n");
      out.write("		<nav class=\"header-nav ms-auto\">\r\n");
      out.write("			<ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item d-block d-lg-none\"><a\r\n");
      out.write("					class=\"nav-link nav-icon search-bar-toggle \" href=\"#\"> <i\r\n");
      out.write("						class=\"bi bi-search\"></i>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<!-- End Search Icon-->\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a class=\"nav-link nav-icon\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\"> <i class=\"bi bi-bell\"></i>\r\n");
      out.write("						<span class=\"badge bg-primary badge-number\">4</span>\r\n");
      out.write("				</a> <!-- End Notification Icon -->\r\n");
      out.write("\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">\r\n");
      out.write("						<li class=\"dropdown-header\">You have 4 new notifications <a\r\n");
      out.write("							href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View\r\n");
      out.write("									all</span></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"notification-item\"><i\r\n");
      out.write("							class=\"bi bi-exclamation-circle text-warning\"></i>\r\n");
      out.write("							<div>\r\n");
      out.write("								<h4>Lorem Ipsum</h4>\r\n");
      out.write("								<p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("								<p>30 min. ago</p>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"notification-item\"><i\r\n");
      out.write("							class=\"bi bi-x-circle text-danger\"></i>\r\n");
      out.write("							<div>\r\n");
      out.write("								<h4>Atque rerum nesciunt</h4>\r\n");
      out.write("								<p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("								<p>1 hr. ago</p>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"notification-item\"><i\r\n");
      out.write("							class=\"bi bi-check-circle text-success\"></i>\r\n");
      out.write("							<div>\r\n");
      out.write("								<h4>Sit rerum fuga</h4>\r\n");
      out.write("								<p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("								<p>2 hrs. ago</p>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"notification-item\"><i\r\n");
      out.write("							class=\"bi bi-info-circle text-primary\"></i>\r\n");
      out.write("							<div>\r\n");
      out.write("								<h4>Dicta reprehenderit</h4>\r\n");
      out.write("								<p>Quae dolorem earum veritatis oditseno</p>\r\n");
      out.write("								<p>4 hrs. ago</p>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"dropdown-footer\"><a href=\"#\">Show all\r\n");
      out.write("								notifications</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul> <!-- End Notification Dropdown Items --></li>\r\n");
      out.write("				<!-- End Notification Nav -->\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown\"><a class=\"nav-link nav-icon\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\"> <i\r\n");
      out.write("						class=\"bi bi-chat-left-text\"></i> <span\r\n");
      out.write("						class=\"badge bg-success badge-number\">3</span>\r\n");
      out.write("				</a> <!-- End Messages Icon -->\r\n");
      out.write("\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">\r\n");
      out.write("						<li class=\"dropdown-header\">You have 3 new messages <a\r\n");
      out.write("							href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">View\r\n");
      out.write("									all</span></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"message-item\"><a href=\"#\"> <img\r\n");
      out.write("								src=\"assets/img/messages-1.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<h4>Maria Hudson</h4>\r\n");
      out.write("									<p>Velit asperiores et ducimus soluta repudiandae labore\r\n");
      out.write("										officia est ut...</p>\r\n");
      out.write("									<p>4 hrs. ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"message-item\"><a href=\"#\"> <img\r\n");
      out.write("								src=\"assets/img/messages-2.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<h4>Anna Nelson</h4>\r\n");
      out.write("									<p>Velit asperiores et ducimus soluta repudiandae labore\r\n");
      out.write("										officia est ut...</p>\r\n");
      out.write("									<p>6 hrs. ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"message-item\"><a href=\"#\"> <img\r\n");
      out.write("								src=\"assets/img/messages-3.jpg\" alt=\"\" class=\"rounded-circle\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<h4>David Muldon</h4>\r\n");
      out.write("									<p>Velit asperiores et ducimus soluta repudiandae labore\r\n");
      out.write("										officia est ut...</p>\r\n");
      out.write("									<p>8 hrs. ago</p>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"dropdown-footer\"><a href=\"#\">Show all messages</a>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("					</ul> <!-- End Messages Dropdown Items --></li>\r\n");
      out.write("				<!-- End Messages Nav -->\r\n");
      out.write("\r\n");
      out.write("				<li class=\"nav-item dropdown pe-3\"><a\r\n");
      out.write("					class=\"nav-link nav-profile d-flex align-items-center pe-0\"\r\n");
      out.write("					href=\"#\" data-bs-toggle=\"dropdown\"> <img\r\n");
      out.write("						src=\"assets/img/profile-img.jpg\" alt=\"Profile\"\r\n");
      out.write("						class=\"rounded-circle\"> <span\r\n");
      out.write("						class=\"d-none d-md-block dropdown-toggle ps-2\">K. Anderson</span>\r\n");
      out.write("				</a> <!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">\r\n");
      out.write("						<li class=\"dropdown-header\">\r\n");
      out.write("							<h6>Kevin Anderson</h6> <span>Web Designer</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"users-profile.html\"> <i class=\"bi bi-person\"></i> <span>My\r\n");
      out.write("									Profile</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"users-profile.html\"> <i class=\"bi bi-gear\"></i> <span>Account\r\n");
      out.write("									Settings</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"pages-faq.html\"> <i class=\"bi bi-question-circle\"></i>\r\n");
      out.write("								<span>Need Help?</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"dropdown-item d-flex align-items-center\"\r\n");
      out.write("							href=\"#\"> <i class=\"bi bi-box-arrow-right\"></i> <span>Sign\r\n");
      out.write("									Out</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul> <!-- End Profile Dropdown Items --></li>\r\n");
      out.write("				<!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Sidebar ======= -->\r\n");
      out.write("  <aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"books\">\r\n");
      out.write("          <i class=\"bi bi-grid\"></i>\r\n");
      out.write("          <span>Trang chủ</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Dashboard Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" data-bs-target=\"#components-nav\" data-bs-toggle=\"collapse\" href=\"#\">\r\n");
      out.write("          <i class=\"bi bi-menu-button-wide\"></i><span>Components</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"components-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-alerts.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Alerts</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-accordion.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Accordion</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-badges.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Badges</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-breadcrumbs.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Breadcrumbs</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-buttons.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Buttons</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-cards.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Cards</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-carousel.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Carousel</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-list-group.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>List group</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-modal.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Modal</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-tabs.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Tabs</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-pagination.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Pagination</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-progress.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Progress</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-spinners.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Spinners</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"components-tooltips.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Tooltips</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li><!-- End Components Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" data-bs-target=\"#forms-nav\" data-bs-toggle=\"collapse\" href=\"books\">\r\n");
      out.write("          <i class=\"bi bi-layout-text-window-reverse\"></i><span>Quản lý sách</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"forms-nav\" class=\"nav-content collapse\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"/library_manager/books\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Danh sách sách</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li><!-- End Forms Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link \" data-bs-target=\"#tables-nav\" data-bs-toggle=\"collapse\" href=\"#\">\r\n");
      out.write("          <i class=\"bi bi-journal-text\"></i><span>Quản lý thành viên</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"tables-nav\" class=\"nav-content collapse show\" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"/library_manager/members\" class=\"active\">\r\n");
      out.write("              <i class=\"bi bi-circle\" ></i><span>Danh sách thành viên</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li><!-- End Tables Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" data-bs-target=\"#charts-nav\" data-bs-toggle=\"collapse\" href=\"#\">\r\n");
      out.write("          <i class=\"bi bi-bar-chart\"></i><span>Charts</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"charts-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"charts-chartjs.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Chart.js</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"charts-apexcharts.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>ApexCharts</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"charts-echarts.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>ECharts</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li><!-- End Charts Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" data-bs-target=\"#icons-nav\" data-bs-toggle=\"collapse\" href=\"#\">\r\n");
      out.write("          <i class=\"bi bi-gem\"></i><span>Icons</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"icons-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"icons-bootstrap.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Bootstrap Icons</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"icons-remix.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Remix Icons</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"icons-boxicons.html\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Boxicons</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li><!-- End Icons Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-heading\">Pages</li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"users-profile.html\">\r\n");
      out.write("          <i class=\"bi bi-person\"></i>\r\n");
      out.write("          <span>Profile</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-faq.html\">\r\n");
      out.write("          <i class=\"bi bi-question-circle\"></i>\r\n");
      out.write("          <span>F.A.Q</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End F.A.Q Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-contact.html\">\r\n");
      out.write("          <i class=\"bi bi-envelope\"></i>\r\n");
      out.write("          <span>Contact</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Contact Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-register.html\">\r\n");
      out.write("          <i class=\"bi bi-card-list\"></i>\r\n");
      out.write("          <span>Register</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Register Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-login.html\">\r\n");
      out.write("          <i class=\"bi bi-box-arrow-in-right\"></i>\r\n");
      out.write("          <span>Login</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Login Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-error-404.html\">\r\n");
      out.write("          <i class=\"bi bi-dash-circle\"></i>\r\n");
      out.write("          <span>Error 404</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Error 404 Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"pages-blank.html\">\r\n");
      out.write("          <i class=\"bi bi-file-earmark\"></i>\r\n");
      out.write("          <span>Blank</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Blank Page Nav -->\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("  </aside><!-- End Sidebar-->\r\n");
      out.write("\r\n");
      out.write("	<main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"pagetitle\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-10\">\r\n");
      out.write("					<h1>Dashboard</h1>\r\n");
      out.write("					<nav>\r\n");
      out.write("						<ol class=\"breadcrumb\">\r\n");
      out.write("							<li class=\"breadcrumb-item\"><a href=\"books\">Home</a></li>\r\n");
      out.write("							<li class=\"breadcrumb-item active\">Quản lý thành viên</li>\r\n");
      out.write("						</ol>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-2\">\r\n");
      out.write("					<a href=\"addMember.jsp\" type=\"\">\r\n");
      out.write("						<button class=\"btn btn-success\">Thêm thành viên</button>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("		<section class=\"section dashboard\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

            		String message = request.getParameter("message");
            		if ("deleteSuccess".equals(message)) {
        		
      out.write("\r\n");
      out.write("        		<script type=\"text/javascript\">\r\n");
      out.write("            		alert('Xóa thành viên thành công!');\r\n");
      out.write("            		window.location.href = 'members';\r\n");
      out.write("        		</script>\r\n");
      out.write("        		");

        		
					}
        		
      out.write("\r\n");
      out.write("        		");

            		if ("updateSuccess".equals(message)) {
        		
      out.write("\r\n");
      out.write("        		<script type=\"text/javascript\">\r\n");
      out.write("            		alert('Sửa thành viên thành công!');\r\n");
      out.write("            		window.location.href = 'members';\r\n");
      out.write("        		</script>\r\n");
      out.write("        		");

				}
        		
      out.write("\r\n");
      out.write("				<table class=\"table table-striped\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"col\">ID</th>\r\n");
      out.write("							<th scope=\"col\">Tên thành viên</th>\r\n");
      out.write("							<th scope=\"col\">Địa chỉ</th>\r\n");
      out.write("							<th scope=\"col\">Số điện thoại</th>\r\n");
      out.write("							<th scope=\"col\">Email</th>\r\n");
      out.write("							<th scope=\"col\">Tác vụ</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

							ArrayList<Member> members = (ArrayList<Member>) request.getAttribute("members");
							for (Member member : members) {
                		
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"row\">");
      out.print( member.getMember_id() );
      out.write("</th>\r\n");
      out.write("							<td>");
      out.print( member.getMember_name() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( member.getMember_address() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( member.getMember_phone() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( member.getMember_email() );
      out.write("</td>\r\n");
      out.write("							<td>\r\n");
      out.write("                        		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/edit-member\" method=\"get\" style=\"display:inline; margin-right: 10px;\">\r\n");
      out.write("                            		<input type=\"hidden\" name=\"memberID\" value=\"");
      out.print(member.getMember_id() );
      out.write("\">\r\n");
      out.write("                            		<button type=\"submit\" class=\"btn btn-primary text-white\">\r\n");
      out.write("                                		<i class=\"bi bi-pencil-square\"></i>\r\n");
      out.write("                            		</button>\r\n");
      out.write("                        		</form>\r\n");
      out.write("								<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delete-member\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("                            		<input type=\"hidden\" name=\"memberID\" value=\"");
      out.print( member.getMember_id() );
      out.write("\">\r\n");
      out.write("                            		<button type=\"submit\" class=\"btn btn-danger text-white\">\r\n");
      out.write("                                		<i class=\"bi bi-trash3\"></i>\r\n");
      out.write("                            		</button>\r\n");
      out.write("                        		</form>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

                    }
                
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Footer ======= -->\r\n");
      out.write("	<footer id=\"footer\" class=\"footer\">\r\n");
      out.write("		<div class=\"copyright\">\r\n");
      out.write("			&copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights\r\n");
      out.write("			Reserved\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"credits\">\r\n");
      out.write("			<!-- All the links in the footer should remain intact. -->\r\n");
      out.write("			<!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("			<!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("			<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->\r\n");
      out.write("			Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("	<a href=\"#\"\r\n");
      out.write("		class=\"back-to-top d-flex align-items-center justify-content-center\"><i\r\n");
      out.write("		class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Vendor JS Files -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/apexcharts.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/js/echarts.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/js/tinymce.min.js\"></script>\r\n");
      out.write("	<script src=\"/js/validate.js\"></script>\r\n");
      out.write("	<!-- Template Main JS File -->\r\n");
      out.write("	<script src=\"/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
